version: '3.4'

networks:
  ijoin-api:
    driver: bridge

services:
  apiweb:
    image: ijoin/apiweb:latest
    depends_on:
      - 'postgres_image'
    build:
      dockerfile: Dockerfile
      context: ./Ema.Ijoins.Api
    ports:
      - '5000:80'
    environment:
      DB_CONNECTION_STRING: 'host=postgres_image;port=5432;database=ema_database;username=ema_user;password=magical_password'
    networks:
      - ijoin-api

  postgres_image:
    image: postgres:latest
    ports:
      - '5432'
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./Ema.postgresql/dbscript.sql :/docker-entrypoint-initdb.d/dbscript.sql
    environment:
      POSTGRES_USER: 'ema_user'
      POSTGRES_PASSWORD: 'magical_password'
      POSTGRES_DB: 'ema_database'
    networks:
      - ijoin-api
volumes:
  db_volume:
