version: '3.4'

networks:
  ijoin-api:
    driver: bridge

services:
  nginx:
    depends_on:
      - apiweb
      - apimobile
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./Ema.Nginx
    ports:
      - '3050:80'
    networks:
      - ijoin-api

  apiweb:
    image: ijoin/apiweb:latest
    depends_on:
      - 'postgres_db'
      - 'mongodb_db'
    build:
      dockerfile: Dockerfile
      context: ./Ema.Ijoins.Api
    environment:
      DB_CONNECTION_STRING: 'host=postgres_db;port=5432;database=ema_database;username=ema_user;password=magical_password'
    networks:
      - ijoin-api

  apimobile:
    image: ijoin/apimobile:latest
    depends_on:
      - 'mongodb_db'
    build:
      dockerfile: Dockerfile
      context: ./Ema.IjoinsChkInOut.Api
    networks:
      - ijoin-api

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./Ema.Admin.Web
    volumes:
      - /app/node_modules
      - ./Ema.Admin.Web:/app
    networks:
      - ijoin-api

  postgres_db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./Ema.Database/dbscript.sql :/docker-entrypoint-initdb.d/dbscript.sql
    environment:
      POSTGRES_USER: 'ema_user'
      POSTGRES_PASSWORD: 'magical_password'
      POSTGRES_DB: 'ema_database'
    networks:
      - ijoin-api

  mongodb_db:
    image: mongo:latest
    ports:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - ijoin-api
