 DROP TABLE public."TBM_USER_SESSION_USER";
 DROP TABLE public."TBM_USER_SEGMENT";
 DROP TABLE public."TBM_USER_SESSION";
 DROP TABLE public."TB_USER_REGISTRATION";
 
 DROP SEQUENCE public."TB_USER_REGISTRATION_id_seq";
