apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-mobile-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server-mobile
  template:
    metadata:
      labels:
        component: server-mobile
    spec:
      containers:
        - name: server-mobile
          image: rattawitdev/multi-server-mobile
          ports:
            - containerPort: 5050
          env:
            - name: DB_USER_PGHOST
              value: postgres-user-cluster-ip-service
            - name: DB_USER_PGPORT
              value: '5432'
            - name: DB_USER_PGDATABASE
              value: userijoin_database
            - name: DB_USER_PGUSER
              value: userijoin_user
            - name: DB_USER_PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: userpgpassword
                  key: USERPGPASSWORD
