apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-mobile-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: servermobile
  template:
    metadata:
      labels:
        component: servermobile
    spec:
      containers:
        - name: servermobile
          image: rattawitdev/multi-server-mobile-k8s
          ports:
            - containerPort: 5050
          env:
            - name: DB_USER_PGHOST
              value: postgres-cluster-ip-service
            - name: DB_USER_PGPORT
              value: '5432'
            - name: DB_USER_PGDATABASE
              value: userijoin_database
            - name: DB_USER_PGUSER
              value: userijoin_user
            - name: DB_USER_PGPASSWORD
              value: userijoin_password
