export const AUTH_BEGIN = 'AUTH_BEGIN';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const EDITFROM_SELECTED = 'EDITFROM_SELECTED';

export const SESSION_SELECTED = 'SESSION_SELECTED';
export const SESSIONUSER_SELECTED = 'SESSIONUSER_SELECTED';
export const ADDDAY_SELECTED = 'ADDDAY_SELECTED';
export const USERASSIGN_SELECTED = 'USERASSIGN_SELECTED';

export const SESSIONS_UPDATE = 'SESSIONS_UPDATE';

export const BEGIN_SESSIONS_API_CALL = 'BEGIN_SESSIONS_API_CALL';
export const FETCH_SESSIONS_SUCCESS = 'FETCH_SESSIONS_SUCCESS';
export const SESSIONS_API_CALL_ERROR = 'SESSIONS_API_CALL_ERROR';

export const BEGIN_REPORT_API_CALL = 'BEGIN_REPORT_API_CALL';
export const FETCH_REPORT_SUCCESS = 'FETCH_REPORT_SUCCESS';
export const REPORT_API_CALL_ERROR = 'REPORT_API_CALL_ERROR';

export const BEGIN_PARTICIPANT_API_CALL = 'BEGIN_PARTICIPANT_API_CALL';
export const FETCH_PARTICIPANT_SUCCESS = 'FETCH_PARTICIPANT_SUCCESS';
export const PARTICIPANT_API_CALL_ERROR = 'PARTICIPANT_API_CALL_ERROR';

export const BEGIN_USERREGIS_API_CALL = 'BEGIN_USERREGIS_API_CALL';
export const FETCH_USERREGIS_SUCCESS = 'FETCH_USERREGIS_SUCCESS';
export const USERREGIS_API_CALL_ERROR = 'USERREGIS_API_CALL_ERROR';

export const BEGIN_TODAY_API_CALL = 'BEGIN_TODAY_API_CALL';
export const FETCH_TODAY_SUCCESS = 'FETCH_TODAY_SUCCESS';
export const TODAY_API_CALL_ERROR = 'TODAY_API_CALL_ERROR';

export const BEGIN_SEVENDAY_API_CALL = 'BEGIN_SEVENDAY_API_CALL';
export const FETCH_SEVENDAY_SUCCESS = 'FETCH_SEVENDAY_SUCCESS';
export const SEVENDAY_API_CALL_ERROR = 'SEVENDAY_API_CALL_ERROR';

export const BEGIN_DAYDASH_API_CALL = 'BEGIN_DAYDASH_API_CALL';
export const FETCH_DAYDASH_SUCCESS = 'FETCH_DAYDASH_SUCCESS';
export const DAYDASH_API_CALL_ERROR = 'DAYDASH_API_CALL_ERROR';
